config/routes.rb
Rails.application.routes.draw do
	root to: redirect("/#{I18n.default_locale}", status: 302)
  get 'auth/:provider/callback', to: 'sessions#create'
  scope "/:locale" do
	  resources :instructions
	  resources :tags, only: [:show]
	  resources :categories
	  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	  root to: 'home#index'
	  get 'home/profile'
	  delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :instructions
	validates :name, presence: true
end

app/models/instruction.rb
class Instruction < ApplicationRecord
	belongs_to :user
  belongs_to :category
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings, dependent: :destroy
  default_scope -> { order('created_at DESC') }

  def all_tags
  	self.tags.map(&:name).join(', ')
  end
  def all_tags=(names)
  	self.tags = names.split(',').map do |name|
  		Tag.where(name: name.strip).first_or_create!
  	end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :instructions, through: :taggings

	def self.counts
		self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :instruction
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :instructions, dependent: :destroy
	def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name']
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
		{ :locale => I18n.locale }
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @instructions = @category.instructions
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
      if @category.save
        redirect_to categories_path, success: 'Category was successfully created.'
      else
        render :new
      end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        redirect_to categories_path, success: 'Category was successfully updated.'
      else
        render :edit
      end
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @instruction = Instruction.all
  end
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_action :set_instruction, only: [:show, :edit, :update, :destroy]
  
  def index
    @instructions = current_user.instructions.all
  end

  def show
  end

  def new
    @instruction = Instruction.new
  end

  def edit
  end

  def create
    @user = current_user
    @instruction = @user.instructions.build(instruction_params)

    respond_to do |format|
      if @instruction.save
        format.html { redirect_to @instruction, notice: 'Instruction was successfully created.' }
        format.json { render :show, status: :created, location: @instruction }
      else
        format.html { render :new }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @instruction.update(instruction_params)
        format.html { redirect_to @instruction, notice: 'Instruction was successfully updated.' }
        format.json { render :show, status: :ok, location: @instruction }
      else
        format.html { render :edit }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @instruction.destroy
    respond_to do |format|
      format.html { redirect_to instructions_url, notice: 'Instruction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_instruction
      @instruction = Instruction.find(params[:id])
      @qr = RQRCode::QRCode.new( @instruction.url_youtube, :size => 4, :level => :h )
    end

    def instruction_params
      params.require(:instruction).permit(:body, :step_id, :category_id, :url_youtube, :all_tags, :title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
    auth = request.env["omniauth.auth"]
    session[:omniauth] = auth.except 'extra'
    user = User.sign_in_from_omniauth auth
    session[:user_id] = user.id
    if user.blocked
      session[:user_id] = nil
      session[:omniauth] = nil
      flash[:danger] = " User BLOCKED"
    else
      flash[:success] = "SIGNED IN"
    end
    redirect_to root_url
  end

  def destroy
   session[:user_id] = nil
   session[:omniauth] = nil
   redirect_to root_url
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by(name: params[:id])
		@instructions = @tag.instructions
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * (classes.size - 1)
			yield(tag, classes[index.round])
		end
	end

	def parse_url(url)
		url.split('/')[3].strip
	end

	def youtube(url)
		"https://www.youtube.com/embed/" + parse_url(url)
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/views/categories/_categories.html.erb
<li>
  <span class="content"><%= category.name %></span>
</li>

app/views/categories/index.html.erb
<div class="buttons_panel">
	<%= link_to '' %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<section id="instructions">
	<%= render @instructions %>
</section>

app/views/home/index.html.erb
<% if @instruction.any? %>
  <ol class="microposts">
    <%= render @instruction %>
  </ol>
<% end %>

app/views/instructions/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
	this.page.url = 'http://localhost.com<%= request.original_fullpath %>/';
	this.page.identifier = '<%= @instruction.id %>';
};
(function() {
	var d = document, s = d.createElement('script');
	s.src = 'https://http-localhost-3000-11.disqus.com/embed.js';
	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                

app/views/instructions/_form.html.erb
<%= form_for(instruction) do |f| %>
  <% if instruction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instruction.errors.count, "error") %> prohibited this instruction from being saved:</h2>

      <ul>
      <% instruction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row control-group">
      <div class="form-group col-xs-12 floating-label-form-group controls">
          <%= f.label :title %>
          <%= f.text_field :title, :placeholder => :title, class: 'form-control' %>
      </div>
  </div>

  <div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls body">
      <%= f.label :body %>
      <%= f.trix_editor :body, :placeholder => :title, class: 'editor' %>
    </div>
  </div><br/>

  <div class="row control-group">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.order(:name), :id, :name, {include_blank: false}, class: 'form-control' %>
  </div>

  <div class="row control-group">
      <div class="form-group col-xs-12 floating-label-form-group controls">
          <%= f.label :url_youtube %>
          <%= f.text_field :url_youtube, :placeholder => :url_youtube, class: 'form-control' %>
      </div>
  </div>

  <div class="row control-group">
      <div class="form-group col-xs-12 floating-label-form-group controls">
          <%= f.label :all_tags %>
          <%= f.text_field :all_tags, :placeholder => :all_tags, class: 'form-control' %>
      </div>
  </div>
  <br/>
  <div class="row">
    <div class="form-group col-xs-12">
      <%= f.submit "Create", class: "btn btn-success btn-lg" %>
      <%= link_to 'Back', instructions_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
<% end %>

app/views/instructions/_instruction.html.erb
<article class="instruction">
	<section class="instruction-head">
		<h2><%= link_to instruction.title, instruction_path(instruction) %></h2>
		<small>
			<time><%= instruction.created_at.to_date.strftime("%d %B, %Y") %></time>
			|
			<%= raw instruction.tags.map(&:name).map{|t| link_to t, tag_path(t)}.join(' / ') %>
		</small>
	</section>
	<section class="instruction-summary">
		<%= instruction.body.html_safe %>
	</section>
</article>

app/views/instructions/edit.html.erb
<h1>Editing Instruction</h1>
<%= link_to 'Back', instructions_path %>
<%= render 'form', instruction: @instruction %>

app/views/instructions/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Instructions</h1>
<%= link_to 'New Instruction', new_instruction_path %>
<% @instructions.each do |instruction| %>
  <section id="instructions">
    <article class="instruction">
      <section class="instruction-head">
        <h2><%= link_to instruction.title, instruction_path(instruction) %></h2>
        <small>
          <time><%= instruction.created_at.to_date.strftime("%d %B, %Y") %></time>
          |
          <% if signed_in? %>
            <%= link_to 'Edit', edit_instruction_path(instruction) %>
            <%= link_to 'Destroy', instruction, method: :delete, data: { confirm: 'Are you sure?' } %>
          |
          <% end %>
          <%= raw instruction.tags.map(&:name).map{|t| link_to t, tag_path(t)}.join(' / ') %>
        </small>
      </section>
      <section class="instruction-summary">
        <%= instruction.body.html_safe %>
      </section>
    </article>
  </section>
<% end %>

app/views/instructions/new.html.erb
<h1>New Instruction</h1>
<%= render 'form', instruction: @instruction %>

app/views/instructions/show.html.erb
<section id="instruction-prev">
  <%= link_to 'Back', instructions_path %>
  <section id="instructions">
    <section class="instruction-head">
      <h2><%= @instruction.title %></h2>
      <small>
        <time><%= @instruction.created_at.to_date.strftime("%d %B, %Y") %></time>
        |
        <%= raw @instruction.tags.map(&:name).map{|t| link_to t, tag_path(t)}.join(' / ') %>
        <% if @instruction.category.present? %>
          |
          <%= link_to @instruction.category.name, @instruction.category %>
        <% end %>
      </small>
    </section>
    <section class="instruction-qr">
      <%= raw @qr.as_html %>
    </section>
    <section class="instruction-summary">
      <%= @instruction.body.html_safe %>
    </section>
    <section class="instruction-video">
      <iframe width="560" height="315" src="<%= youtube(@instruction.url_youtube) %>" frameborder="0" allowfullscreen></iframe>
    </section>
  </section>
  <%= render 'disqus'%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  </head>
  <body>
    <nav id="mainNav" class="navbar navbar-default navbar-custom">
      <div class="container">
          <div class="navbar-header page-scroll">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
              </button>
              <%= link_to "Home", '/', class: "navbar-brand" %>
              <%= link_to "RU", "/ru" %>
              <%= link_to "EN", "/en" %>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <% if signed_in? %>
                    <li class="page-scroll"><%= link_to "Admin", rails_admin_path %></li>
                    <li class="page-scroll"><%= link_to "Manual", instructions_path %></li>
                    <li class="page-scroll"><%= link_to "Sign out", sign_out_path, method: :delete %></li>
                    <li class="page-scroll user-info">Signed in as <span><%= current_user.name %></span></li>
                  <% else %>
                    <li class="page-scroll"><%= link_to "Log in with Twitter", "/auth/twitter" %></li>
                    <li class="page-scroll"><%= link_to "Log in with Facebook", "/auth/facebook" %></li>
                    <li class="page-scroll"><%= link_to "Log in with Vkontakte", "/auth/vkontakte" %></li>
                  <% end %>
              </ul>
          </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <%= render 'partial/submenu' %>
          <div class="tags-cloud">
            <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3}) do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
            <% end %>
          </div>
        </div>
        <div class="col-md-9">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>    
        </div>
      </div>
    </div>
  </body>
</html>

app/views/partial/_submenu.html.erb
<div class="submenu">
	<ul class="nav flex-column">
		<% Category.all.each do |category| %>
			<li class="nav-item">
				<%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category))}" %>
			</li>
		<% end %>
	</ul>
</div>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<% if @tag.instructions.empty? %>
   <h2>Blank</h2>
<% else %>
   <%= render @tag.instructions %>
<% end %>